### PR TITLE
Update organize_data.py for mip_era discovery

### LINKED ISSUE #20: Deal with sidepot data
The "sidepot" data is an accumulating resource that needs to deal with both CMIP5 and CMIP5 (and CMIP3) data, some tweaks enable mip_era to be identified

### PR DESCRIPTION
**Pull request by durack1**
Fix #20 

@pochedls take a peek at this, should solve the CMIP5/6 issue

### CODE REVIEW

**Comment by pochedls** [comment]
Thanks @durack1 - I think this will work. 

To test, you can grab the fileArchive:

`/export_backup/pochedley1/code/xagg/tools/fileArchive.mat`

and place files into: 

`/p/user_pub/xclim/extension/wget`

The purpose of the fileArchive was to remember what has already been added to this side pot. There are flags about what to do if repeat files are added (`deleteRepeats` and `overCopyRepeats`). Perhaps it makes most sense to set `deleteRepeats = False` and `overCopyRepeats = True` so that when data is added it updates the side pot and results in a regeneration of the xml.

**Comment by durack1** [comment]
With the files that @covey1 has grabbed, these will need to be added to the xclim sir somewhere, did you already have a directory structure at add to?

**Comment by pochedls** [comment]
They get added here: https://github.com/pochedls/xagg/blob/da6910a331ad1e01393af9ed24094a0f623b826b/tools/organize_data.py#L26

But this should be done using the script, which remembers that they were added.

**Comment by pochedls** [comment]
Though - now that I think about it - you probably need more logic to deal with fx files.

**Comment by durack1** [comment]
Sorry should’ve been clearer, for persistent paths, as Curt dropped these into his home dir and these will not likely remain in that location long, it’s better that these files get migrated into the main /p tree somewhere so that we can index once and not be sensitive to user changes

**Comment by pochedls** [comment]
@durack1 - the files need to be places into the wget directory I reference above. They are then moved into a directory structure that is picked up by xagg.

**Comment by durack1** [comment]
@pochedls ok so to be clear, you have a bunch of wget*.sh files in the `wget/archive` subdir, which makes me think you are **trying** to keep some idea of a log from when and where these files appeared, correct?

**Comment by pochedls** [comment]
Hi Paul - those were previous wget files I had. I archived rather than deleting, but this wasn't organized or necessary. This was originally my sidepot (that everyone could see), then mark started adding data (that I also wanted). We could delete this directory or archive stuff there.

**Comment by durack1** [comment]
@pochedls should this be closed or merged?

**Comment by pochedls** [comment]
@durack1 - I don't think this was ever tested?

**Comment by durack1** [comment]
I didn't have write access for the directory at the time, so stopped.. If I remember correctly

**Comment by pochedls** [comment]
Feel free to give yourself write access (I do not have privileges to do that). Please backup `fileArchive.mat` during testing.

**Comment by durack1** [comment]
@pochedls is `fileArchive.mat` meant to live here? Can't see it:
```python
(base) bash-4.2$ ls -al ../xclim/extension/                                                                                                                                                                                                                                                                            
drwxr-x---  32768 May 20 08:23 .                                                                                                                 
drwxrwxr-x   4096 May 22 12:14 ..                                                                                                                
drwxr-x---   4096 Apr 23  2019 CMIP5                                                                                                             
drwxr-x---   4096 May 20 08:29 CMIP6                                                                                                             
drwxr-x--- 262144 May 20 08:29 wget                                                                                                              
-rw-rw-rw-     25 Apr 23  2019 .wget-20190423231747.sh.status 
```

**Comment by durack1** [comment]
Does it make sense to move this into the same location as the data, and keep it there? Otherwise, it needs to be committed to the repo, so that edits can update and then commit this (my preference is the former)

**Comment by pochedls** [comment]
Sure - it could be moved with the data.

**Comment by durack1** [comment]
@pochedls I am really confused why there are two commits from you in this PR, will close this and open a new one to see if I can get untangled

**Comment by pochedls** [comment]
I'm not totally sure. I made some commits to master. Maybe if they affect files you are working on they get merged into your PR automatically?

**Comment by durack1** [comment]
@pochedls I got very confused, #25 fixed me up though, just running some tests now (after breakfast)

**Comment by durack1** [comment]
@pochedls have you hit an issue with `scandir` before:
```python
(cdmcduNompiN200618) bash-4.2$ python organize_data.py 
Traceback (most recent call last):
  File "organize_data.py", line 24, in <module>
    import fx
  File "../fx.py", line 46, in <module>
    import scandir
ModuleNotFoundError: No module named 'scandir'
(cdmcduNompiN200618) bash-4.2$ conda install scandir
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - scandir -> python[version='>=2.7,<2.8.0a0']

Your python: python=3.6

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.
```

**Comment by pochedls** [comment]
@durack1 - I have not needed to recreate this environment in awhile. I used the formula under [Setup](https://github.com/pochedls/xagg).

**Comment by durack1** [comment]
It seems that `scandir` was subsumed into `os` for Py3.5. I assume you are currently working with Py2 for these libraries?

**Comment by durack1** [comment]
Actually, it seems the `scandir` implementation in Py3 is incomplete, there is no `walk` member in the `os.scandir` implementation.

So surely, you must be using an env that is py2 with scandir installed alongside?

**Comment by pochedls** [comment]
@durack1 - did you follow the instructions in the documentation? They work with version 4.8.2. 

`conda create -n xagg -c conda-forge -c cdat cdms2 joblib scandir`

**Comment by durack1** [comment]
@pochedls nope, I had forgotten about the specifics. Following the recipe in the instructions yields:
```python
Weird, so it's pulling the source from conda-forge:
```python
(base) bash-4.2$ conda create -n xagg -c conda-forge -c cdat cdms2 joblib scandir
...
  added / updated specs:
    - cdms2
    - joblib
    - scandir
...
  joblib             conda-forge/noarch::joblib-0.15.1-py_0
...
  libnetcdf          conda-forge/linux-64::libnetcdf-4.7.4-nompi_h84807e1_104
...
  numpy              conda-forge/linux-64::numpy-1.18.5-py38h8854b6b_0
... 
  python             conda-forge/linux-64::python-3.8.2-he5300dc_7_cpython
...
  scandir            conda-forge/linux-64::scandir-1.10.0-py38h1e0a361_1
...
```
So it seems I just need to behave myself and use the dedicated env

**Comment by durack1** [comment]
@pochedls as an aside, it does seem like [`scandir` has all been bolted into py3.5+](https://github.com/benhoyt/scandir) so remapping to `os.walk` could reduce dependency by one. Maybe worth investigating when time stops

**Pull request closed without merging**
